#!/usr/bin/env bash

DIR=${DIR:-build}

# Requires the following 2 JAR files to be executables in the $PATH
CLOSURE_STYLESHEETS_JAR="$(which closure-stylesheets.jar)"
HTML_COMPRESSOR_JAR="$(which htmlcompressor.jar)"
test -f "$CLOSURE_STYLESHEETS_JAR" && test -f "$HTML_COMPRESSOR_JAR" || exit 1

# Minify HTML
find $DIR -type f -name '*.html' -exec java -jar "$HTML_COMPRESSOR_JAR" --remove-intertag-spaces '{}' --output '{}' \;
# Minify CSS
find $DIR -type f -name '*.css' -exec java -jar "$CLOSURE_STYLESHEETS_JAR" --allow-unrecognized-properties '{}' --output-file '{}' \;
# Compress files
find $DIR -type f -exec zopfli --i1000 '{}' \;
